name: Run Azure Login with OIDC
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPLICATIONID }}
          tenant-id: ${{ secrets.TENANTIDTENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
